/**
 * HomeStyler 디자인 토큰 이식
 * 원본: docs/homestyler_design_system/DESIGN.md frontmatter
 *       (+ docs/_1/code.html 의 Stitch tailwind.config)
 * 클래스명 = 토큰명: bg-primary, text-on-surface, font-label-sm, text-body-md 등
 */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#464555',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
        'surface-tint': '#4d44e3',
        primary: '#3525cd',
        'on-primary': '#ffffff',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        'inverse-primary': '#c3c0ff',
        secondary: '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        tertiary: '#703a00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#934e00',
        'on-tertiary-container': '#ffd2b1',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#6e3900',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
      },
      fontFamily: {
        'headline-xl': ['Plus Jakarta Sans', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
        'body-lg': ['Inter', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
        'body-md': ['Inter', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
        'body-sm': ['Inter', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
        'label-md': ['Inter', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
        'label-sm': ['Inter', 'Pretendard Variable', 'Pretendard', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '20px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      maxWidth: {
        container: '1280px',
      },
    },
  },
  plugins: [],
};
